import 'package:amazon_clone/models/models.Dart';

final List<Product> products = [
  Product(
      id: '1',
      title: "HP 24mh FHD Monitor",
      price: 164.99,
      rating: 5,
      image:
          'https://images-na.ssl-images-amazon.com/images/I/91fAU6mxFsL._AC_SL1500_.jpg'),
  Product(
      id: '2',
      title: "NexiGo AutoFocus 1080p ",
      price: 54.99,
      rating: 5,
      image:
          'https://images-na.ssl-images-amazon.com/images/I/61BGZKR0OBL._AC_SL1500_.jpg'),
  Product(
      id: '3',
      title: "Blue Yeti USB Mic for Recording & Streaming on PC and Mac ",
      price: 129.98,
      rating: 5,
      image:
          'https://images-na.ssl-images-amazon.com/images/I/61Ly9zgVyIL._AC_SL1500_.jpg')
];
